[versions]
androidMinSdk = "21"
androidTargetSdk = "34"
androidCompileSdk = "34"

versionName = "2.8.2-beta01"
versionCode = "140"

jvmTarget = "17"
compose-compiler = "1.5.14"

imageToolboxLibs = "1.6.2"

avifCoderCoil = "1.7.5"
avifCoder = "1.7.5"
aire = "0.11.4"
jxlCoderCoil = "2.2.0"
jxlCoder = "2.2.0"

tesseract = "4.7.0"
composeVersion = "1.7.0-beta02"
androidx-datastorePreferencesAndroid = "1.1.1"
appUpdateKtx = "2.1.0"
appUpdate = "2.1.0"
shadowGadgets = "2.2.1"
fadingEdges = "1.0.4"
firebaseCrashlyticsKtx = "19.0.1"
konfettiCompose = "2.0.4"
reimagined = "1.5.0"
shadowsPlus = "1.0.4"
exifinterface = "1.3.7"
firebaseAnalyticsKtx = "22.0.1"
firebaseCrashlyticsGradle = "3.0.1"
google-segmentationSelfie = "16.0.0-beta5"
google-subjectSegmentation = "16.0.0-beta1"
detekt = "1.23.6"
detektCompose = "0.4.4"

kotlin = "1.9.24"
agp = "8.4.1"
hilt = "2.51.1"
gms = "4.4.2"

coil = "2.6.0"
appCompat = "1.7.0"
androidxCore = "1.13.1"
androidxLifecycle = "2.8.1"
desugaring = "2.0.4"
activityCompose = "1.9.0"
kotlinxCollectionsImmutable = "0.3.7"
scrollbar = "2.1.0"
material3 = "1.3.0-beta02"
reorderable = "0.9.6"
reviewKtx = "2.0.1"
splashScreen = "1.2.0-alpha01"

espresso = "3.5.1"
ksp = "1.9.24-1.0.20"

androidx-test-ext-junit = "1.1.5"
documentfile = "1.0.1"
uiautomator = "2.3.0"
androidxMacroBenchmark = "1.3.0-alpha05"
quickieBundled = "1.10.0"
quickieFoss = "1.11.0"

material = "1.13.0-alpha02"

documentScanner = "1.3.7"
mlkitDocumentScanner = "16.0.0-beta1"
zxingAndroidEmbedded = "4.3.0"
capturable = "2.1.0"

[libraries]
mlkit-document-scanner = { module = "com.google.android.gms:play-services-mlkit-document-scanner", version.ref = "mlkitDocumentScanner" }
quickie-bundled = { module = "io.github.g00fy2.quickie:quickie-bundled", version.ref = "quickieBundled" }
quickie-foss = { module = "com.github.T8RIN:quickie-foss", version.ref = "quickieFoss" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
capturable = { module = "dev.shreyaspatil:capturable", version.ref = "capturable" }
documentscanner = { module = "com.github.T8RIN:DocumentScanner", version.ref = "documentScanner" }
imageToolboxLibs = { module = "com.github.T8RIN:ImageToolboxLibs", version.ref = "imageToolboxLibs" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
aire = { module = "com.github.awxkee:aire", version.ref = "aire" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeVersion" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "composeVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
avif-coder = { module = "com.github.awxkee:avif-coder", version.ref = "avifCoder" }
avif-coder-coil = { module = "com.github.awxkee:avif-coder-coil", version.ref = "avifCoderCoil" }
compose = { module = "com.github.zed-alpha.shadow-gadgets:compose", version.ref = "shadowGadgets" }
datastore-preferences-android = { module = "androidx.datastore:datastore-preferences-android", version.ref = "androidx-datastorePreferencesAndroid" }
fadingEdges = { module = "com.github.t8rin:ComposeFadingEdges", version.ref = "fadingEdges" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
konfetti-compose = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfettiCompose" }
reimagined = { module = "dev.olshevski.navigation:reimagined", version.ref = "reimagined" }
reimagined-hilt = { module = "dev.olshevski.navigation:reimagined-hilt", version.ref = "reimagined" }
shadowsPlus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "shadowsPlus" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coilGif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coilSvg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
jxl-coder-coil = { module = "io.github.awxkee:jxl-coder-coil", version.ref = "jxlCoderCoil" }
jxl-coder = { module = "io.github.awxkee:jxl-coder", version.ref = "jxlCoder" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
scrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "scrollbar" }
mlkit-segmentation-selfie = { module = "com.google.mlkit:segmentation-selfie", version.ref = "google-segmentationSelfie" }
mlkit-subject-segmentation = { module = "com.google.android.gms:play-services-mlkit-subject-segmentation", version.ref = "google-subjectSegmentation" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
tesseract = { module = "cz.adaptech.tesseract4android:tesseract4android-openmp", version.ref = "tesseract" }

firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
baselineprofile-gradle = { group = "androidx.benchmark", name = "benchmark-baseline-profile-gradle-plugin", version.ref = "androidxMacroBenchmark" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
gms-gradle = { module = "com.google.gms:google-services", version.ref = "gms" }
kotlinx-serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
ksp-gradle = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }

[plugins]
image-toolbox-library = { id = "image.toolbox.library", version = "unspecified" }
image-toolbox-hilt = { id = "image.toolbox.hilt", version = "unspecified" }
image-toolbox-feature = { id = "image.toolbox.feature", version = "unspecified" }
image-toolbox-compose = { id = "image.toolbox.compose", version = "unspecified" }