[versions]
androidMinSdk = "21"
androidTargetSdk = "35"
androidCompileSdk = "35"

versionName = "3.1.2-alpha01"
versionCode = "162"

jvmTarget = "17"

imageToolboxLibs = "3.2.5"
trickle = "1.2.2"

avifCoder = "2.0.10"
avifCoderCoil = "2.0.10"
aire = "0.15.5"
jxlCoder = "2.4.0.5"
jxlCoderCoil = "2.4.0.6"
jpegliCoder = "1.0.1"

tesseract = "4.8.0"
material3 = "1.4.0-alpha05"
composeVersion = "1.8.0-alpha07"
materialIconsExtended = "1.7.6"
androidx-datastorePreferencesAndroid = "1.1.1"
appUpdateKtx = "2.1.0"
appUpdate = "2.1.0"
shadowGadgets = "2.3.0"
fadingEdges = "1.0.4"
firebaseCrashlyticsKtx = "19.3.0"
konfettiCompose = "2.0.5"
shadowsPlus = "1.0.4"
exifinterface = "1.4.0-alpha01"
firebaseAnalyticsKtx = "22.1.2"
firebaseCrashlyticsGradle = "3.0.2"
google-segmentationSelfie = "16.0.0-beta6"
google-subjectSegmentation = "16.0.0-beta1"
detekt = "1.23.7"
detektCompose = "0.4.22"
decompose = "3.2.2"

kotlin = "2.0.21"
agp = "8.7.3"
hilt = "2.53.1"
gms = "4.4.2"

ktor = "3.0.3"
coil = "3.0.4"
appCompat = "1.7.0"
androidxCore = "1.15.0"
androidxLifecycle = "2.9.0-alpha08"
desugaring = "2.1.3"
activityCompose = "1.10.0-rc01"
kotlinxCollectionsImmutable = "0.3.8"
scrollbar = "2.2.0"
reorderable = "2.4.2"
reviewKtx = "2.0.2"
splashScreen = "1.2.0-alpha02"

espresso = "3.6.1"
ksp = "2.0.21-1.0.28"

androidx-test-ext-junit = "1.2.1"
documentfile = "1.0.1"
uiautomator = "2.3.0"
androidxMacroBenchmark = "1.4.0-alpha06"
quickie = "1.13.1"

material = "1.13.0-alpha09"
jsoup = "1.18.3"

documentScanner = "1.3.7"
mlkitDocumentScanner = "16.0.0-beta1"
zxingAndroidEmbedded = "4.3.0"
capturable = "3.0.1"
moshi = "1.15.2"
aboutlibraries = "11.2.3"
junit = "4.13.2"

[libraries]
aboutlibraries-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
trickle = { module = "com.github.t8rin:trickle", version.ref = "trickle" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
mlkit-document-scanner = { module = "com.google.android.gms:play-services-mlkit-document-scanner", version.ref = "mlkitDocumentScanner" }
quickie-bundled = { module = "com.github.T8RIN.QuickieExtended:quickie-bundled", version.ref = "quickie" }
quickie-foss = { module = "com.github.T8RIN.QuickieExtended:quickie-foss", version.ref = "quickie" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
capturable = { module = "dev.shreyaspatil:capturable", version.ref = "capturable" }
documentscanner = { module = "com.github.T8RIN:DocumentScanner", version.ref = "documentScanner" }

toolbox-cropper = { module = "com.github.T8RIN.ImageToolboxLibs:cropper", version.ref = "imageToolboxLibs" }
toolbox-dynamicTheme = { module = "com.github.T8RIN.ImageToolboxLibs:dynamic-theme", version.ref = "imageToolboxLibs" }
toolbox-colordetector = { module = "com.github.T8RIN.ImageToolboxLibs:colordetector", version.ref = "imageToolboxLibs" }
toolbox-gesture = { module = "com.github.T8RIN.ImageToolboxLibs:gesture", version.ref = "imageToolboxLibs" }
toolbox-beforeafter = { module = "com.github.T8RIN.ImageToolboxLibs:beforeafter", version.ref = "imageToolboxLibs" }
toolbox-image = { module = "com.github.T8RIN.ImageToolboxLibs:image", version.ref = "imageToolboxLibs" }
toolbox-screenshot = { module = "com.github.T8RIN.ImageToolboxLibs:screenshot", version.ref = "imageToolboxLibs" }
toolbox-modalsheet = { module = "com.github.T8RIN.ImageToolboxLibs:modalsheet", version.ref = "imageToolboxLibs" }
toolbox-gpuimage = { module = "com.github.T8RIN.ImageToolboxLibs:gpuimage", version.ref = "imageToolboxLibs" }
toolbox-colorpicker = { module = "com.github.T8RIN.ImageToolboxLibs:colorpicker", version.ref = "imageToolboxLibs" }
toolbox-systemuicontroller = { module = "com.github.T8RIN.ImageToolboxLibs:systemuicontroller", version.ref = "imageToolboxLibs" }
toolbox-placeholder = { module = "com.github.T8RIN.ImageToolboxLibs:placeholder", version.ref = "imageToolboxLibs" }
toolbox-logger = { module = "com.github.T8RIN.ImageToolboxLibs:logger", version.ref = "imageToolboxLibs" }
toolbox-zoomable = { module = "com.github.T8RIN.ImageToolboxLibs:zoomable", version.ref = "imageToolboxLibs" }
toolbox-extendedcolors = { module = "com.github.T8RIN.ImageToolboxLibs:extendedcolors", version.ref = "imageToolboxLibs" }
toolbox-androidwm = { module = "com.github.T8RIN.ImageToolboxLibs:androidwm", version.ref = "imageToolboxLibs" }
toolbox-gifConverter = { module = "com.github.T8RIN.ImageToolboxLibs:gif-converter", version.ref = "imageToolboxLibs" }
toolbox-apng = { module = "com.github.T8RIN.ImageToolboxLibs:apng", version.ref = "imageToolboxLibs" }
toolbox-snowfall = { module = "com.github.T8RIN.ImageToolboxLibs:snowfall", version.ref = "imageToolboxLibs" }
toolbox-svg = { module = "com.github.T8RIN.ImageToolboxLibs:svg", version.ref = "imageToolboxLibs" }
toolbox-jp2decoder = { module = "com.github.T8RIN.ImageToolboxLibs:jp2decoder", version.ref = "imageToolboxLibs" }
toolbox-tiffDecoder = { module = "com.github.T8RIN.ImageToolboxLibs:tiffdecoder", version.ref = "imageToolboxLibs" }
toolbox-qoiCoder = { module = "com.github.T8RIN.ImageToolboxLibs:qoi-coder", version.ref = "imageToolboxLibs" }
toolbox-awebp = { module = "com.github.T8RIN.ImageToolboxLibs:awebp", version.ref = "imageToolboxLibs" }
toolbox-psd = { module = "com.github.T8RIN.ImageToolboxLibs:psd", version.ref = "imageToolboxLibs" }
toolbox-djvuCoder = { module = "com.github.T8RIN.ImageToolboxLibs:djvu-coder", version.ref = "imageToolboxLibs" }
toolbox-fastNoise = { module = "com.github.T8RIN.ImageToolboxLibs:fast-noise", version.ref = "imageToolboxLibs" }
toolbox-collages = { module = "com.github.T8RIN.ImageToolboxLibs:collages", version.ref = "imageToolboxLibs" }
toolbox-histogram = { module = "com.github.T8RIN.ImageToolboxLibs:histogram", version.ref = "imageToolboxLibs" }
toolbox-uCrop = { module = "com.github.T8RIN.ImageToolboxLibs:ucrop", version.ref = "imageToolboxLibs" }
toolbox-opencvTools = { module = "com.github.T8RIN.ImageToolboxLibs:opencv-tools", version.ref = "imageToolboxLibs" }
toolbox-curves = { module = "com.github.T8RIN.ImageToolboxLibs:curves", version.ref = "imageToolboxLibs" }

aire = { module = "com.github.awxkee:aire", version.ref = "aire" }
jpegli-coder = { module = "com.github.awxkee:jpegli-coder", version.ref = "jpegliCoder" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeVersion" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
avif-coder = { module = "com.github.awxkee:avif-coder", version.ref = "avifCoder" }
avif-coder-coil = { module = "com.github.awxkee:avif-coder-coil", version.ref = "avifCoderCoil" }
shadowGadgets = { module = "com.github.zed-alpha.shadow-gadgets:compose", version.ref = "shadowGadgets" }
datastore-preferences-android = { module = "androidx.datastore:datastore-preferences-android", version.ref = "androidx-datastorePreferencesAndroid" }
fadingEdges = { module = "com.github.t8rin:ComposeFadingEdges", version.ref = "fadingEdges" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
konfetti-compose = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfettiCompose" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decomposeExtensions = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
shadowsPlus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "shadowsPlus" }

ktor = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
coilNetwork = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coilCompose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilGif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coilSvg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }

firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
jxl-coder-coil = { module = "io.github.awxkee:jxl-coder-coil", version.ref = "jxlCoderCoil" }
jxl-coder = { module = "io.github.awxkee:jxl-coder", version.ref = "jxlCoder" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
scrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "scrollbar" }
mlkit-segmentation-selfie = { module = "com.google.mlkit:segmentation-selfie", version.ref = "google-segmentationSelfie" }
mlkit-subject-segmentation = { module = "com.google.android.gms:play-services-mlkit-subject-segmentation", version.ref = "google-subjectSegmentation" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
tesseract = { module = "cz.adaptech.tesseract4android:tesseract4android-openmp", version.ref = "tesseract" }

firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
baselineprofile-gradle = { group = "androidx.benchmark", name = "benchmark-baseline-profile-gradle-plugin", version.ref = "androidxMacroBenchmark" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
gms-gradle = { module = "com.google.gms:google-services", version.ref = "gms" }
kotlinx-serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
ksp-gradle = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
aboutlibraries-gradle = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutlibraries" }
compose-compiler-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

# Used in convention plugins
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }

androidx-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "composeVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
image-toolbox-library = { id = "image.toolbox.library", version = "unspecified" }
image-toolbox-hilt = { id = "image.toolbox.hilt", version = "unspecified" }
image-toolbox-feature = { id = "image.toolbox.feature", version = "unspecified" }
image-toolbox-compose = { id = "image.toolbox.compose", version = "unspecified" }
image-toolbox-application = { id = "image.toolbox.application", version = "unspecified" }