[versions]
androidMinSdk = "21"
androidTargetSdk = "34"
androidCompileSdk = "34"
versionName = "2.5.2"
versionCode = "106"
jvmTarget = "17"

composeColorDetector = "1.0.0"
composeColorfulSliders = "1.2.0"
composeExtendedColors = "1.0.0-alpha07"
m3color = "2023.10.1"
paletteKtx = "1.0.0"
uiText = "1.6.0-beta03"
androidx-datastorePreferencesAndroid = "1.1.0-alpha07"
androidx-material = "1.6.0-beta03"
appUpdateKtx = "2.1.0"
appUpdate = "2.1.0"
avifCoder = "1.5.8"
jxlCoder = "1.5.7"
compose = "2.1.0"
fadingEdges = "1.0.3"
firebaseCrashlyticsKtx = "18.6.0"
konfettiCompose = "2.0.4"
reimagined = "1.5.0"
shadowsPlus = "1.0.4"
exifinterface = "1.3.7"
firebaseAnalyticsKtx = "21.5.0"
firebaseCrashlyticsGradle = "2.9.9"
google-segmentationSelfie = "16.0.0-beta4"
hiltCompiler = "1.1.0"

compose-compiler = "1.5.7"
kotlin = "1.9.21"
agp = "8.2.0"
hilt = "2.50"
gms = "4.4.0"

coil = "2.5.0"
coroutines = "1.7.3"
androidx = "1.6.1"
androidxCore = "1.12.0"
androidxLifecycle = "2.6.2"
desugaring = "2.0.4"
firebaseBom = "32.2.2"
firebaseGms = "18.3.0"
composeBom = "2023.10.01"
decompose = "2.2.2"
activityCompose = "1.8.2"
kotlinxCollectionsImmutable = "0.3.7"
scrollbar = "1.8.0"
material3 = "1.2.0-beta01"
material3WindowSizeClass = "beta01"
materialIconsExtended = "1.6.0-beta03"
reorderable = "0.9.6"
reviewKtx = "2.0.1"
splashScreen = "1.0.1"
room = "2.6.1"
hiltJetpack = "1.0.0"

leakCanary = "2.7"
junit = "4.13.2"
runner = "1.5.2"
espresso = "3.5.1"
mockito = "4.8.0"
testArchCore = "2.1.0"
testCoroutines = "1.7.3"
kotlinxSerializationJson = "1.6.2"
ksp = "1.9.22-1.0.16"

androidx-test-ext-junit = "1.1.5"
material = "1.11.0"
documentfile = "1.0.1"
uiautomator = "2.2.0"
androidxMacroBenchmark = "1.2.2"

bitmapscaler = "1.0.2"

[libraries]
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialIconsExtended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "uiText" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
avif-coder = { module = "com.github.awxkee:avif-coder", version.ref = "avifCoder" }
compose = { module = "com.github.zed-alpha.shadow-gadgets:compose", version.ref = "compose" }
compose-color-detector = { module = "com.github.SmartToolFactory:Compose-Color-Detector", version.ref = "composeColorDetector" }
compose-colorful-sliders = { module = "com.github.SmartToolFactory:Compose-Colorful-Sliders", version.ref = "composeColorfulSliders" }
compose-extended-colors = { module = "com.github.SmartToolFactory:Compose-Extended-Colors", version.ref = "composeExtendedColors" }
datastore-preferences-android = { module = "androidx.datastore:datastore-preferences-android", version.ref = "androidx-datastorePreferencesAndroid" }
fadingEdges = { module = "com.github.GIGAMOLE:ComposeFadingEdges", version.ref = "fadingEdges" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
konfetti-compose = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfettiCompose" }
m3color = { module = "com.github.Kyant0:m3color", version.ref = "m3color" }
reimagined = { module = "dev.olshevski.navigation:reimagined", version.ref = "reimagined" }
reimagined-hilt = { module = "dev.olshevski.navigation:reimagined-hilt", version.ref = "reimagined" }
shadowsPlus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "shadowsPlus" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coilGif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coilSvg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
jxl-coder-coil = { module = "com.github.awxkee:jxl-coder-coil", version.ref = "jxlCoder" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
scrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "scrollbar" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
mlkit-segmentation-selfie = { module = "com.google.mlkit:segmentation-selfie", version.ref = "google-segmentationSelfie" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decomposeExtensions = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
viewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger = { module = "com.google.dagger:dagger", version.ref = "hilt" }
room = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }

gms = { module = "com.google.android.gms:play-services-base", version.ref = "firebaseGms" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockitoKotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito" }
testArchCore = { module = "android.arch.core:core-testing", version.ref = "testArchCore" }
testCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "testCoroutines" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
runner = { module = "androidx.test:runner", version.ref = "runner" }

hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
kotlin-reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
t8rin-bitmapscaler = { group = "com.github.t8rin", name = "bitmapscaler", version.ref="bitmapscaler" }

firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
baselineprofile-gradle = { group = "androidx.benchmark", name = "benchmark-baseline-profile-gradle-plugin", version.ref = "androidxMacroBenchmark" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
gms-gradle = { module = "com.google.gms:google-services", version.ref = "gms" }
kotlinx-serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
ksp-gradle = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }